[project]
name = "auth-py-js"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "opaque>=0.2.0",
    "pysodium>=0.7.18",
]
